[project]
name = "firefinder"
version = "0.1.0"
description = "Firefinder Python project."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-circuitpython-mlx90640>=1.3.3",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]

[project.scripts]
firefinder-camera-demo = "cam_demo.camera_demo:main"
firefinder-mlx-demo = "mlx_demo.main:main"
firefinder-camera-mlx-demo = "cam_mlx_demo.main:main"
firefinder-object-detection-demo = "cam_demo.object_detection_demo:main"

[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
target-version = "py311"
